"""
V3Cube-derived seed data for SB Drive VTC.
Extracted from sbdriv5_db2024.sql and sbdriv5_beta24.sql.
"""

# ============================
# VEHICLE CATEGORIES (Ride types)
# Maps to MySQL vehicle_category table
# ============================
VEHICLE_CATEGORIES = [
    {
        "id": "vcat_vtc_taxi",
        "slug": "vtc-taxi",
        "name_en": "VTC-Taxi",
        "name_fr": "VTC-Taxi",
        "type": "Ride",
        "cat_type": "RideCategory",
        "icon": "Car",
        "display_order": 1,
        "status": "active",
        "description_fr": "Réservez votre chauffeur en un clic",
    },
    {
        "id": "vcat_moto",
        "slug": "moto",
        "name_en": "Moto",
        "name_fr": "Moto",
        "type": "Ride",
        "cat_type": "RideCategory",
        "icon": "Bike",
        "display_order": 2,
        "status": "active",
        "description_fr": "Transport rapide en moto",
    },
    {
        "id": "vcat_rental",
        "slug": "rental",
        "name_en": "Vehicle Rental with Driver",
        "name_fr": "Location avec chauffeur",
        "type": "Ride",
        "cat_type": "RideCategory",
        "icon": "Car",
        "display_order": 3,
        "status": "active",
        "description_fr": "Louez un véhicule avec chauffeur privé",
    },
    {
        "id": "vcat_pool",
        "slug": "pool",
        "name_en": "Pool",
        "name_fr": "Pool-partage",
        "type": "Ride",
        "cat_type": "RideCategory",
        "icon": "Car",
        "display_order": 4,
        "status": "active",
        "description_fr": "Partagez votre trajet et économisez",
    },
    {
        "id": "vcat_schedule",
        "slug": "schedule",
        "name_en": "Plan your trip",
        "name_fr": "Planifier votre course",
        "type": "Ride",
        "cat_type": "RideCategory",
        "icon": "Car",
        "display_order": 5,
        "status": "active",
        "description_fr": "Réservez un trajet à l'avance",
    },
    {
        "id": "vcat_corporate",
        "slug": "corporate",
        "name_en": "Book trips for your employees",
        "name_fr": "Réservez des trajets pour vos employés",
        "type": "Ride",
        "cat_type": "RideCategory",
        "icon": "Car",
        "display_order": 6,
        "status": "active",
        "description_fr": "Réservation entreprise pour vos collaborateurs",
    },
    {
        "id": "vcat_book_other",
        "slug": "book-for-other",
        "name_en": "Book for Someone Else",
        "name_fr": "Réserver pour un proche",
        "type": "Ride",
        "cat_type": "RideCategory",
        "icon": "Car",
        "display_order": 7,
        "status": "active",
        "description_fr": "Réservez un trajet pour quelqu'un d'autre",
    },
    {
        "id": "vcat_bid_taxi",
        "slug": "bid-taxi",
        "name_en": "Bid for Taxi",
        "name_fr": "Negociez le prix",
        "type": "Ride",
        "cat_type": "Bidding",
        "icon": "Car",
        "display_order": 8,
        "status": "active",
        "description_fr": "Négociez le prix de votre course",
    },
    {
        "id": "vcat_intercity",
        "slug": "intercity",
        "name_en": "Intercity Carpooling",
        "name_fr": "Covoiturage inter-villes",
        "type": "Ride",
        "cat_type": "RideCategory",
        "icon": "Car",
        "display_order": 9,
        "status": "active",
        "description_fr": "Voyagez entre les villes en covoiturage",
    },
    {
        "id": "vcat_delivery",
        "slug": "delivery",
        "name_en": "Delivery",
        "name_fr": "Livraison",
        "type": "Deliver",
        "cat_type": "DeliverCategory",
        "icon": "Package",
        "display_order": 10,
        "status": "active",
        "description_fr": "Envoyez et recevez des colis facilement",
    },
]

# ============================
# VEHICLE TYPES (pricing tiers)
# Maps to MySQL vehicle_type table
# ============================
VEHICLE_TYPES = [
    {
        "id": "vtype_sb",
        "slug": "sb",
        "name_en": "SB",
        "name_fr": "SB",
        "category_slug": "vtc-taxi",
        "fare_type": "Regular",
        "base_fare": 1.00,
        "price_per_km": 1.00,
        "price_per_min": 0.10,
        "price_per_hour": 0.0,
        "fixed_fare": 0.0,
        "min_fare": 10.00,
        "commission_percent": 10.0,
        "pickup_price": 1.20,
        "night_price": 0.0,
        "person_capacity": 4,
        "icon_type": "Car",
        "service_type": "Ride",
        "cancellation_fare": 5.0,
        "cancellation_time_limit": 10,
        "waiting_fees": 0.50,
        "waiting_time_limit": 15,
        "status": "active",
        "display_order": 1,
    },
    {
        "id": "vtype_confort",
        "slug": "confort",
        "name_en": "Confort",
        "name_fr": "Confort",
        "category_slug": "vtc-taxi",
        "fare_type": "Regular",
        "base_fare": 2.00,
        "price_per_km": 1.50,
        "price_per_min": 0.15,
        "price_per_hour": 0.0,
        "fixed_fare": 0.0,
        "min_fare": 15.00,
        "commission_percent": 10.0,
        "pickup_price": 1.50,
        "night_price": 0.0,
        "person_capacity": 4,
        "icon_type": "Car",
        "service_type": "Ride",
        "cancellation_fare": 5.0,
        "cancellation_time_limit": 10,
        "waiting_fees": 0.60,
        "waiting_time_limit": 15,
        "status": "active",
        "display_order": 2,
    },
    {
        "id": "vtype_luxe",
        "slug": "luxe",
        "name_en": "Luxury",
        "name_fr": "Luxe",
        "category_slug": "vtc-taxi",
        "fare_type": "Regular",
        "base_fare": 5.00,
        "price_per_km": 2.50,
        "price_per_min": 0.25,
        "price_per_hour": 0.0,
        "fixed_fare": 0.0,
        "min_fare": 25.00,
        "commission_percent": 15.0,
        "pickup_price": 2.00,
        "night_price": 0.0,
        "person_capacity": 4,
        "icon_type": "Car",
        "service_type": "Ride",
        "cancellation_fare": 10.0,
        "cancellation_time_limit": 10,
        "waiting_fees": 1.00,
        "waiting_time_limit": 15,
        "status": "active",
        "display_order": 3,
    },
    {
        "id": "vtype_moto",
        "slug": "moto",
        "name_en": "Moto",
        "name_fr": "Moto",
        "category_slug": "moto",
        "fare_type": "Regular",
        "base_fare": 1.00,
        "price_per_km": 0.80,
        "price_per_min": 0.08,
        "price_per_hour": 0.0,
        "fixed_fare": 0.0,
        "min_fare": 5.00,
        "commission_percent": 10.0,
        "pickup_price": 0.80,
        "night_price": 0.0,
        "person_capacity": 1,
        "icon_type": "Bike",
        "service_type": "Ride",
        "cancellation_fare": 3.0,
        "cancellation_time_limit": 5,
        "waiting_fees": 0.30,
        "waiting_time_limit": 10,
        "status": "active",
        "display_order": 4,
    },
    {
        "id": "vtype_pool",
        "slug": "pool",
        "name_en": "Pool",
        "name_fr": "Pool",
        "category_slug": "pool",
        "fare_type": "Regular",
        "base_fare": 0.50,
        "price_per_km": 0.70,
        "price_per_min": 0.05,
        "price_per_hour": 0.0,
        "fixed_fare": 0.0,
        "min_fare": 5.00,
        "commission_percent": 10.0,
        "pickup_price": 0.80,
        "night_price": 0.0,
        "person_capacity": 4,
        "icon_type": "Car",
        "service_type": "Ride",
        "cancellation_fare": 3.0,
        "cancellation_time_limit": 5,
        "waiting_fees": 0.30,
        "waiting_time_limit": 10,
        "status": "active",
        "display_order": 5,
    },
    {
        "id": "vtype_suv",
        "slug": "suv",
        "name_en": "SUV",
        "name_fr": "SUV",
        "category_slug": "vtc-taxi",
        "fare_type": "Regular",
        "base_fare": 3.00,
        "price_per_km": 2.00,
        "price_per_min": 0.20,
        "price_per_hour": 0.0,
        "fixed_fare": 0.0,
        "min_fare": 20.00,
        "commission_percent": 12.0,
        "pickup_price": 1.80,
        "night_price": 0.0,
        "person_capacity": 6,
        "icon_type": "Car",
        "service_type": "Ride",
        "cancellation_fare": 8.0,
        "cancellation_time_limit": 10,
        "waiting_fees": 0.80,
        "waiting_time_limit": 15,
        "status": "active",
        "display_order": 6,
    },
    {
        "id": "vtype_electric",
        "slug": "electric",
        "name_en": "Electric",
        "name_fr": "Electrique",
        "category_slug": "vtc-taxi",
        "fare_type": "Regular",
        "base_fare": 1.50,
        "price_per_km": 1.20,
        "price_per_min": 0.12,
        "price_per_hour": 0.0,
        "fixed_fare": 0.0,
        "min_fare": 12.00,
        "commission_percent": 10.0,
        "pickup_price": 1.30,
        "night_price": 0.0,
        "person_capacity": 4,
        "icon_type": "Car",
        "service_type": "Ride",
        "cancellation_fare": 5.0,
        "cancellation_time_limit": 10,
        "waiting_fees": 0.50,
        "waiting_time_limit": 15,
        "status": "active",
        "display_order": 7,
    },
    {
        "id": "vtype_van",
        "slug": "van",
        "name_en": "Van",
        "name_fr": "Van",
        "category_slug": "vtc-taxi",
        "fare_type": "Regular",
        "base_fare": 4.00,
        "price_per_km": 2.20,
        "price_per_min": 0.20,
        "price_per_hour": 0.0,
        "fixed_fare": 0.0,
        "min_fare": 22.00,
        "commission_percent": 12.0,
        "pickup_price": 2.00,
        "night_price": 0.0,
        "person_capacity": 8,
        "icon_type": "Car",
        "service_type": "Ride",
        "cancellation_fare": 8.0,
        "cancellation_time_limit": 10,
        "waiting_fees": 0.80,
        "waiting_time_limit": 15,
        "status": "active",
        "display_order": 8,
    },
    {
        "id": "vtype_accessible",
        "slug": "accessible",
        "name_en": "Accessible",
        "name_fr": "Accessible",
        "category_slug": "vtc-taxi",
        "fare_type": "Regular",
        "base_fare": 2.00,
        "price_per_km": 1.50,
        "price_per_min": 0.15,
        "price_per_hour": 0.0,
        "fixed_fare": 0.0,
        "min_fare": 12.00,
        "commission_percent": 10.0,
        "pickup_price": 1.50,
        "night_price": 0.0,
        "person_capacity": 4,
        "icon_type": "Car",
        "service_type": "Ride",
        "cancellation_fare": 5.0,
        "cancellation_time_limit": 10,
        "waiting_fees": 0.50,
        "waiting_time_limit": 15,
        "status": "active",
        "display_order": 9,
    },
    {
        "id": "vtype_airport",
        "slug": "airport",
        "name_en": "Airport",
        "name_fr": "Aeroport",
        "category_slug": "vtc-taxi",
        "fare_type": "Fixed",
        "base_fare": 0.0,
        "price_per_km": 0.0,
        "price_per_min": 0.0,
        "price_per_hour": 0.0,
        "fixed_fare": 55.00,
        "min_fare": 55.00,
        "commission_percent": 12.0,
        "pickup_price": 0.0,
        "night_price": 0.0,
        "person_capacity": 4,
        "icon_type": "Car",
        "service_type": "Ride",
        "cancellation_fare": 10.0,
        "cancellation_time_limit": 15,
        "waiting_fees": 1.00,
        "waiting_time_limit": 20,
        "status": "active",
        "display_order": 10,
    },
    {
        "id": "vtype_pets",
        "slug": "pets",
        "name_en": "Pet Friendly",
        "name_fr": "Animaux",
        "category_slug": "vtc-taxi",
        "fare_type": "Regular",
        "base_fare": 2.50,
        "price_per_km": 1.60,
        "price_per_min": 0.15,
        "price_per_hour": 0.0,
        "fixed_fare": 0.0,
        "min_fare": 14.00,
        "commission_percent": 10.0,
        "pickup_price": 2.00,
        "night_price": 0.0,
        "person_capacity": 4,
        "icon_type": "Car",
        "service_type": "Ride",
        "cancellation_fare": 5.0,
        "cancellation_time_limit": 10,
        "waiting_fees": 0.60,
        "waiting_time_limit": 15,
        "status": "active",
        "display_order": 11,
    },
    {
        "id": "vtype_tuktuk",
        "slug": "tuktuk",
        "name_en": "TukTuk",
        "name_fr": "TukTuk",
        "category_slug": "moto",
        "fare_type": "Regular",
        "base_fare": 1.50,
        "price_per_km": 0.90,
        "price_per_min": 0.08,
        "price_per_hour": 0.0,
        "fixed_fare": 0.0,
        "min_fare": 6.00,
        "commission_percent": 10.0,
        "pickup_price": 1.00,
        "night_price": 0.0,
        "person_capacity": 3,
        "icon_type": "Bike",
        "service_type": "Ride",
        "cancellation_fare": 3.0,
        "cancellation_time_limit": 5,
        "waiting_fees": 0.30,
        "waiting_time_limit": 10,
        "status": "active",
        "display_order": 12,
    },
    {
        "id": "vtype_assist",
        "slug": "assist",
        "name_en": "Assist",
        "name_fr": "Assistance",
        "category_slug": "vtc-taxi",
        "fare_type": "Regular",
        "base_fare": 3.00,
        "price_per_km": 1.60,
        "price_per_min": 0.15,
        "price_per_hour": 0.0,
        "fixed_fare": 0.0,
        "min_fare": 15.00,
        "commission_percent": 8.0,
        "pickup_price": 2.00,
        "night_price": 0.0,
        "person_capacity": 4,
        "icon_type": "Car",
        "service_type": "Ride",
        "cancellation_fare": 5.0,
        "cancellation_time_limit": 10,
        "waiting_fees": 0.50,
        "waiting_time_limit": 20,
        "status": "active",
        "display_order": 13,
    },
    {
        "id": "vtype_vtc",
        "slug": "vtc",
        "name_en": "VTC",
        "name_fr": "VTC",
        "category_slug": "vtc-taxi",
        "fare_type": "Regular",
        "base_fare": 2.50,
        "price_per_km": 1.60,
        "price_per_min": 0.15,
        "price_per_hour": 0.0,
        "fixed_fare": 0.0,
        "min_fare": 15.00,
        "commission_percent": 12.0,
        "pickup_price": 1.50,
        "night_price": 0.0,
        "person_capacity": 4,
        "icon_type": "Car",
        "service_type": "Ride",
        "cancellation_fare": 6.0,
        "cancellation_time_limit": 10,
        "waiting_fees": 0.60,
        "waiting_time_limit": 15,
        "status": "active",
        "display_order": 14,
        "allowed_taxi_subs": ["vtc"],
    },
    {
        "id": "vtype_taxi",
        "slug": "taxi",
        "name_en": "Taxi",
        "name_fr": "Taxi",
        "category_slug": "vtc-taxi",
        "fare_type": "Regular",
        "base_fare": 2.80,
        "price_per_km": 1.70,
        "price_per_min": 0.18,
        "price_per_hour": 0.0,
        "fixed_fare": 0.0,
        "min_fare": 16.00,
        "commission_percent": 12.0,
        "pickup_price": 1.60,
        "night_price": 0.0,
        "person_capacity": 4,
        "icon_type": "Car",
        "service_type": "Ride",
        "cancellation_fare": 6.0,
        "cancellation_time_limit": 10,
        "waiting_fees": 0.60,
        "waiting_time_limit": 15,
        "status": "active",
        "display_order": 15,
        "allowed_taxi_subs": ["taxi"],
    },

]

# ============================
# MASTER SERVICE CATEGORIES
# Maps to MySQL master_service_category table
# ============================
MASTER_SERVICE_CATEGORIES = [
    {"id": "mscat_taxi", "slug": "taxi", "name_en": "Taxi", "name_fr": "Taxi", "type": "Ride", "status": "active", "display_order": 1},
    {"id": "mscat_delivery", "slug": "delivery", "name_en": "Delivery", "name_fr": "Livraison", "type": "Deliver", "status": "active", "display_order": 2},
    {"id": "mscat_services", "slug": "services", "name_en": "On-Demand Services", "name_fr": "Services à la demande", "type": "UberX", "status": "active", "display_order": 3},
    {"id": "mscat_video", "slug": "video-consult", "name_en": "Video Consulting", "name_fr": "Consultation Vidéo", "type": "VideoConsult", "status": "active", "display_order": 4},
    {"id": "mscat_bidding", "slug": "bidding", "name_en": "Post a Task", "name_fr": "Publier une tâche", "type": "Bidding", "status": "active", "display_order": 5},
    {"id": "mscat_medical", "slug": "medical", "name_en": "Medical Services", "name_fr": "Services Médicaux", "type": "MedicalServices", "status": "active", "display_order": 6},
]

# ============================
# SERVICE CATEGORIES (UberX / On-demand)
# Enriched from V3Cube with French translations
# ============================
SERVICE_CATEGORIES = {
    "beauty": {
        "name_fr": "Beauté",
        "name_en": "Beauty",
        "icon": "Scissors",
        "services": [
            {"slug": "hair-care", "name_fr": "Soins Capillaires", "name_en": "Hair Care"},
            {"slug": "facial", "name_fr": "Soins Visage", "name_en": "Facial"},
            {"slug": "nails", "name_fr": "Ongles & Manucure", "name_en": "Nails & Manicure"},
            {"slug": "waxing", "name_fr": "Épilation", "name_en": "Waxing"},
            {"slug": "makeup", "name_fr": "Maquillage & Coiffure", "name_en": "Makeup & Hairstyling"},
            {"slug": "massage-spa", "name_fr": "Massage & Spa", "name_en": "Massage & Spa"},
            {"slug": "men-grooming", "name_fr": "Soins Hommes", "name_en": "Men Grooming"},
            {"slug": "hands-feet", "name_fr": "Mains & Pieds", "name_en": "Hands & Feet"},
            {"slug": "eyebrows-lashes", "name_fr": "Sourcils & Cils", "name_en": "Eyebrows & Lashes"},
            {"slug": "exfoliation", "name_fr": "Exfoliation", "name_en": "Exfoliation"},
            {"slug": "tanning", "name_fr": "Bronzage", "name_en": "Tanning"},
            {"slug": "wedding", "name_fr": "Mariage & Pré-Mariage", "name_en": "Wedding & Pre-Wedding"},
        ],
    },
    "pet": {
        "name_fr": "Animaux",
        "name_en": "Pet Care",
        "icon": "PawPrint",
        "services": [
            {"slug": "grooming", "name_fr": "Toilettage", "name_en": "Grooming"},
            {"slug": "walking", "name_fr": "Promenade", "name_en": "Walking"},
            {"slug": "training", "name_fr": "Dressage", "name_en": "Training"},
            {"slug": "boarding", "name_fr": "Pension", "name_en": "Boarding"},
            {"slug": "sitting", "name_fr": "Garde", "name_en": "Sitting"},
            {"slug": "vet", "name_fr": "Soins Vétérinaires", "name_en": "Veterinary Care"},
            {"slug": "pet-spa", "name_fr": "Spa & Bien-être", "name_en": "Spa & Wellness"},
            {"slug": "nutrition", "name_fr": "Alimentation & Nutrition", "name_en": "Food & Nutrition"},
            {"slug": "accessories", "name_fr": "Accessoires & Fournitures", "name_en": "Accessories & Supplies"},
            {"slug": "transport", "name_fr": "Transport", "name_en": "Transport"},
            {"slug": "adoption", "name_fr": "Adoption & Élevage", "name_en": "Adoption & Breeding"},
            {"slug": "photo-events", "name_fr": "Photos & Événements", "name_en": "Photos & Events"},
        ],
    },
    "car-care": {
        "name_fr": "Entretien Auto",
        "name_en": "Car Care",
        "icon": "Car",
        "services": [
            {"slug": "car-wash", "name_fr": "Lavage Auto & Spa", "name_en": "Car Wash & Spa"},
            {"slug": "battery", "name_fr": "Service Batterie", "name_en": "Battery Service"},
            {"slug": "shop", "name_fr": "Boutique", "name_en": "Shop"},
            {"slug": "fuel", "name_fr": "Livraison Carburant", "name_en": "Fuel Delivery"},
            {"slug": "moto-wash", "name_fr": "Lavage Moto & Spa", "name_en": "Moto Wash & Spa"},
            {"slug": "ev-charge", "name_fr": "Recharge EV", "name_en": "EV Charging"},
            {"slug": "car-keys", "name_fr": "Clés Auto", "name_en": "Car Keys"},
            {"slug": "oil-change", "name_fr": "Vidange", "name_en": "Oil Change"},
        ],
    },
    "towing": {
        "name_fr": "Dépannage",
        "name_en": "Towing",
        "icon": "Truck",
        "services": [
            {"slug": "emergency-tow", "name_fr": "Remorquage Urgence", "name_en": "Emergency Towing"},
            {"slug": "flatbed-tow", "name_fr": "Remorquage Plateau", "name_en": "Flatbed Towing"},
            {"slug": "vehicle-recovery", "name_fr": "Récupération Véhicule", "name_en": "Vehicle Recovery"},
            {"slug": "flat-tire", "name_fr": "Pneu Crevé", "name_en": "Flat Tire"},
            {"slug": "lockout", "name_fr": "Ouverture Porte", "name_en": "Lockout Service"},
            {"slug": "jump-start", "name_fr": "Démarrage", "name_en": "Jump Start"},
            {"slug": "fuel-delivery", "name_fr": "Panne Sèche", "name_en": "Fuel Delivery"},
            {"slug": "battery-replacement", "name_fr": "Changement Batterie", "name_en": "Battery Replacement"},
            {"slug": "ev-tow-charge", "name_fr": "Recharge EV", "name_en": "EV Charging"},
        ],
    },
    "medical": {
        "name_fr": "Services Médicaux",
        "name_en": "Medical Services",
        "icon": "Stethoscope",
        "services": [
            {"slug": "appointment", "name_fr": "Prendre Rendez-vous", "name_en": "Book Appointment"},
            {"slug": "video-consult", "name_fr": "Vidéo Consultation", "name_en": "Video Consultation"},
            {"slug": "pharmacy", "name_fr": "Pharmacie", "name_en": "Pharmacy"},
            {"slug": "ambulance", "name_fr": "Ambulance", "name_en": "Ambulance"},
        ],
    },
    "handyman": {
        "name_fr": "Services à la demande",
        "name_en": "Handyman Services",
        "icon": "Wrench",
        "services": [
            {"slug": "handyman", "name_fr": "Bricolage", "name_en": "Handyman"},
            {"slug": "electrician", "name_fr": "Électricien", "name_en": "Electrician"},
            {"slug": "plumber", "name_fr": "Plombier", "name_en": "Plumber"},
            {"slug": "carpenter", "name_fr": "Menuisier", "name_en": "Carpenter"},
            {"slug": "painter", "name_fr": "Peintres", "name_en": "Painters"},
            {"slug": "cleaning", "name_fr": "Ménage Maison", "name_en": "House Cleaning"},
        ],
    },
}

# ============================
# NEARBY BUSINESS CATEGORIES
# Maps to MySQL nearby_category table
# ============================
NEARBY_CATEGORIES = [
    {"id": "ncat_restaurants", "slug": "restaurants", "name_en": "Restaurants", "name_fr": "Restaurants", "display_order": 1},
    {"id": "ncat_cafes", "slug": "cafes", "name_en": "Cafes", "name_fr": "Cafés", "display_order": 2},
    {"id": "ncat_grocery", "slug": "grocery", "name_en": "Grocery Stores", "name_fr": "Épiceries", "display_order": 3},
    {"id": "ncat_pharmacy", "slug": "pharmacy", "name_en": "Pharmacy Stores", "name_fr": "Pharmacies", "display_order": 4},
    {"id": "ncat_salons", "slug": "salons", "name_en": "Salons", "name_fr": "Salons", "display_order": 5},
    {"id": "ncat_spa", "slug": "spa", "name_en": "Spa", "name_fr": "Spa", "display_order": 6},
    {"id": "ncat_shopping", "slug": "shopping", "name_en": "Shopping", "name_fr": "Shopping", "display_order": 7},
    {"id": "ncat_events", "slug": "events", "name_en": "Events", "name_fr": "Événements", "display_order": 8},
    {"id": "ncat_hospital", "slug": "hospital", "name_en": "Hospital", "name_fr": "Hôpital", "display_order": 9},
    {"id": "ncat_gyms", "slug": "gyms", "name_en": "Gyms", "name_fr": "Salles de sport", "display_order": 10},
    {"id": "ncat_malls", "slug": "malls", "name_en": "Malls", "name_fr": "Centres commerciaux", "display_order": 11},
    {"id": "ncat_bars", "slug": "bars", "name_en": "Bars", "name_fr": "Bars", "display_order": 12},
    {"id": "ncat_parks", "slug": "parks", "name_en": "Parks", "name_fr": "Parcs", "display_order": 13},
    {"id": "ncat_museums", "slug": "museums", "name_en": "Museums", "name_fr": "Musées", "display_order": 14},
    {"id": "ncat_attractions", "slug": "attractions", "name_en": "Attractions", "name_fr": "Attractions", "display_order": 15},
    {"id": "ncat_libraries", "slug": "libraries", "name_en": "Libraries", "name_fr": "Bibliothèques", "display_order": 16},
    {"id": "ncat_nightlife", "slug": "nightlife", "name_en": "Nightlife", "name_fr": "Vie nocturne", "display_order": 17},
    {"id": "ncat_hotels", "slug": "hotels", "name_en": "Hotels", "name_fr": "Hôtels", "display_order": 18},
    {"id": "ncat_parking", "slug": "parking", "name_en": "Parking", "name_fr": "Parking", "display_order": 19},
    {"id": "ncat_car_repair", "slug": "car-repair", "name_en": "Car Repair", "name_fr": "Réparation automobile", "display_order": 20},
    {"id": "ncat_other", "slug": "other", "name_en": "Other", "name_fr": "Autre", "display_order": 21},
]

# ============================
# PARCEL DELIVERY TYPES
# Maps to MySQL genie_package_types table
# ============================
PARCEL_PACKAGE_TYPES = [
    {"id": "pkg_food", "slug": "home-food", "name_en": "Home Food", "name_fr": "Nourriture Maison", "display_order": 1},
    {"id": "pkg_care", "slug": "care-packages", "name_en": "Care Packages", "name_fr": "Forfaits de soins", "display_order": 2},
    {"id": "pkg_documents", "slug": "documents", "name_en": "Documents", "name_fr": "Documents", "display_order": 3},
    {"id": "pkg_clothes", "slug": "clothes", "name_en": "Clothes", "name_fr": "Vêtements", "display_order": 4},
    {"id": "pkg_repair", "slug": "repair-items", "name_en": "Items for Repair", "name_fr": "Articles à réparer", "display_order": 5},
]

# ============================
# CANCEL REASONS
# Maps to MySQL cancel_reason table
# ============================
CANCEL_REASONS = [
    {"id": "cr_1", "slug": "changed-mind", "reason_en": "Changed mind?", "reason_fr": "Changement d'avis ?", "for": "User", "display_order": 1},
    {"id": "cr_2", "slug": "driver-didnt-come", "reason_en": "Driver didn't come", "reason_fr": "Le chauffeur n'est pas venu", "for": "User", "display_order": 2},
    {"id": "cr_3", "slug": "driver-wrong-dest", "reason_en": "Driver denied to go to destination", "reason_fr": "Le chauffeur refuse d'aller à la destination", "for": "User", "display_order": 3},
    {"id": "cr_4", "slug": "driver-bad-behaviour", "reason_en": "Driver's behaviour was bad", "reason_fr": "Le comportement du chauffeur était mauvais", "for": "User", "display_order": 4},
    {"id": "cr_5", "slug": "no-mask", "reason_en": "The driver does not have a mask", "reason_fr": "Le chauffeur ne porte pas de masque", "for": "User", "display_order": 5},
    {"id": "cr_6", "slug": "wrong-direction", "reason_en": "The driver goes in another direction", "reason_fr": "Le chauffeur va dans une autre direction", "for": "User", "display_order": 6},
    {"id": "cr_7", "slug": "customer-wrong-location", "reason_en": "Customer gives incorrect location", "reason_fr": "Le client a donné un mauvais emplacement", "for": "Driver", "display_order": 7},
    {"id": "cr_8", "slug": "customer-bad-behaviour", "reason_en": "Customer's behaviour is bad", "reason_fr": "Le comportement du client était mauvais", "for": "Driver", "display_order": 8},
    {"id": "cr_9", "slug": "customer-not-arriving", "reason_en": "Customer is not arriving", "reason_fr": "Le client ne se présente pas", "for": "Driver", "display_order": 9},
    {"id": "cr_10", "slug": "other", "reason_en": "Other reason", "reason_fr": "Autre raison", "for": "Both", "display_order": 10},
]

# ============================
# TRACK SERVICE CATEGORIES (Family tracking)
# Maps to MySQL track_service_category table
# ============================
TRACK_CATEGORIES = [
    {"id": "tcat_family", "slug": "family", "name_en": "Family Members", "name_fr": "Membres de la famille"},
    {"id": "tcat_employees", "slug": "employees", "name_en": "Employees", "name_fr": "Employés"},
]

# ============================
# APP CONFIGURATIONS
# Key settings from MySQL configurations table
# ============================
APP_CONFIGURATIONS = [
    # General
    {"key": "COMPANY_NAME", "value": "SB Drive VTC", "category": "General"},
    {"key": "ADMIN_EMAIL", "value": "contact@sbdrivevtc.com", "category": "General"},
    {"key": "SUPPORT_MAIL", "value": "contact@sbdrivevtc.com", "category": "General"},
    {"key": "NOREPLY_EMAIL", "value": "no-reply@sbdrivevtc.com", "category": "General"},
    {"key": "SUPPORT_PHONE", "value": "FR +33753572145 - Mart +596696681552- CI +2250718168696", "category": "General"},
    {"key": "COMPANY_ADDRESS", "value": "6 Boulevard du general gallieni 93600 Aulnay-Sous-Bois France", "category": "General"},
    {"key": "DEFAULT_CURRENCY_CODE", "value": "EUR", "category": "General"},
    {"key": "DEFAULT_CURRENCY_SIGN", "value": "EUR", "category": "General"},
    {"key": "DEFAULT_COUNTRY_CODE", "value": "FR", "category": "General"},
    {"key": "DEFAULT_DISTANCE_UNIT", "value": "KMs", "category": "General"},
    {"key": "SITE_ISD_CODE", "value": "33", "category": "General"},
    {"key": "SITE_NAME", "value": "SB Drive VTC", "category": "General"},
    {"key": "SYSTEM_TIME_ZONE", "value": "Europe/Paris", "category": "General"},
    # App Settings
    {"key": "APP_MODE", "value": "Production", "category": "App Settings"},
    {"key": "APP_TYPE", "value": "Ride", "category": "App Settings"},
    {"key": "WALLET_ENABLE", "value": "Yes", "category": "App Settings"},
    {"key": "WALLET_FIXED_AMOUNT_1", "value": "10", "category": "App Settings"},
    {"key": "WALLET_FIXED_AMOUNT_2", "value": "50", "category": "App Settings"},
    {"key": "WALLET_FIXED_AMOUNT_3", "value": "100", "category": "App Settings"},
    {"key": "REFERRAL_SCHEME_ENABLE", "value": "Yes", "category": "App Settings"},
    {"key": "REFERRAL_AMOUNT", "value": "5", "category": "App Settings"},
    {"key": "ENABLE_TIP_MODULE", "value": "Yes", "category": "App Settings"},
    {"key": "ENABLE_HAIL_RIDES", "value": "Yes", "category": "App Settings"},
    {"key": "ENABLE_CORPORATE_PROFILE", "value": "Yes", "category": "App Settings"},
    {"key": "RIDE_LATER_BOOKING_ENABLED", "value": "Yes", "category": "App Settings"},
    {"key": "POOL_ENABLE", "value": "Yes", "category": "App Settings"},
    {"key": "BOOK_FOR_ELSE_ENABLE", "value": "Yes", "category": "App Settings"},
    {"key": "HANDICAP_ACCESSIBILITY_OPTION", "value": "No", "category": "App Settings"},
    {"key": "FEMALE_RIDE_REQ_ENABLE", "value": "No", "category": "App Settings"},
    {"key": "CALLMASKING_ENABLED", "value": "Yes", "category": "App Settings"},
    {"key": "RIDE_DRIVER_CALLING_METHOD", "value": "Voip-VideoCall", "category": "App Settings"},
    {"key": "ENABLE_FAVORITE_DRIVER_MODULE", "value": "Yes", "category": "App Settings"},
    {"key": "ENABLE_STOPOVER_POINT", "value": "Yes", "category": "App Settings"},
    {"key": "MAX_NUMBER_STOP_OVER_POINTS", "value": "3", "category": "App Settings"},
    {"key": "ENABLE_DRIVER_DESTINATIONS", "value": "Yes", "category": "App Settings"},
    {"key": "ENABLE_SAFETY_TOOLS", "value": "Yes", "category": "App Settings"},
    {"key": "ENABLE_ACCOUNT_DELETION", "value": "Yes", "category": "App Settings"},
    {"key": "ENABLE_GIFT_CARD_FEATURE", "value": "Yes", "category": "App Settings"},
    {"key": "GIFT_CARD_MAX_AMOUNT", "value": "1000", "category": "App Settings"},
    {"key": "DONATION_ENABLE", "value": "Yes", "category": "App Settings"},
    {"key": "ENABLE_OPEN_STREET_MAP_SERVICE", "value": "Yes", "category": "App Settings"},
    # Ride
    {"key": "RIDER_REQUEST_ACCEPT_TIME", "value": "30", "category": "Ride"},
    {"key": "RESTRICTION_KM_NEAREST_TAXI", "value": "25", "category": "Ride"},
    {"key": "DRIVER_LOC_UPDATE_TIME_INTERVAL", "value": "8", "category": "Ride"},
    {"key": "DRIVER_LOC_FETCH_TIME_INTERVAL", "value": "10", "category": "Ride"},
    {"key": "DRIVER_ARRIVED_MIN_TIME_PER_MINUTE", "value": "5", "category": "Ride"},
    {"key": "DRIVER_ARRIVAL_DISTANCE_TO_USER_PICKUP_ADDRESS", "value": "300", "category": "Ride"},
    {"key": "ENABLE_OTP_RIDE", "value": "No", "category": "Ride"},
    # Prices
    {"key": "ADMIN_COMMISSION", "value": "10", "category": "Prices"},
    {"key": "MIN_ORDER_CANCELLATION_CHARGES", "value": "10", "category": "Prices"},
    # Wallet
    {"key": "WALLET_MIN_BALANCE", "value": "1", "category": "Wallet"},
    {"key": "GOPAY_MAXIMUM_LIMIT_PER_TRANSACTION", "value": "200", "category": "Wallet"},
    {"key": "GOPAY_MAXIMUM_LIMIT_PER_DAY", "value": "200", "category": "Wallet"},
    {"key": "CREDIT_TO_WALLET_ENABLE", "value": "Yes", "category": "Wallet"},
    {"key": "ENABLE_WALLET_WITHDRAWAL_FLOW_DRIVERS", "value": "Yes", "category": "Wallet"},
    {"key": "ENABLE_WALLET_WITHDRAWAL_REQUEST", "value": "Yes", "category": "Wallet"},
    # Verification
    {"key": "RIDER_EMAIL_VERIFICATION", "value": "Yes", "category": "Verification"},
    {"key": "RIDER_PHONE_VERIFICATION", "value": "Yes", "category": "Verification"},
    {"key": "DRIVER_EMAIL_VERIFICATION", "value": "Yes", "category": "Verification"},
    {"key": "DRIVER_PHONE_VERIFICATION", "value": "Yes", "category": "Verification"},
    # Payment
    {"key": "APP_PAYMENT_MODE", "value": "Cash,Card,Wallet", "category": "Payment"},
    {"key": "STRIPE_STATUS", "value": "Active", "category": "Payment"},
    {"key": "STRIPE_MINIMUM_AMOUNT", "value": "0.50", "category": "Payment"},
    {"key": "ORANGEMONEY_STATUS", "value": "Active", "category": "Payment"},
    {"key": "MTN_STATUS", "value": "Active", "category": "Payment"},
    # Tips
    {"key": "TIP_AMOUNT_1", "value": "10", "category": "Tips"},
    {"key": "TIP_AMOUNT_2", "value": "15", "category": "Tips"},
    {"key": "TIP_AMOUNT_3", "value": "20", "category": "Tips"},
    {"key": "RIDE_TIP_AMOUNT_1", "value": "10", "category": "Tips"},
    {"key": "RIDE_TIP_AMOUNT_2", "value": "20", "category": "Tips"},
    {"key": "RIDE_TIP_AMOUNT_3", "value": "30", "category": "Tips"},
    # Social links
    {"key": "FB_LINK_FOOTER", "value": "https://www.facebook.com/sbdrivevtc2018", "category": "Social"},
    {"key": "TWITTER_LINK_FOOTER", "value": "https://x.com/sbdrivevtc", "category": "Social"},
    {"key": "LINKEDIN_LINK_FOOTER", "value": "https://www.linkedin.com/in/sb-drive-513254bb/", "category": "Social"},
    {"key": "INSTAGRAM_LINK_FOOTER", "value": "https://www.instagram.com/sb_drive_vtc/", "category": "Social"},
    {"key": "ANDROID_APP_LINK", "value": "https://play.google.com/store/apps/details?id=com.sbdrivervtc.client", "category": "Social"},
    {"key": "IPHONE_APP_LINK", "value": "https://apps.apple.com/us/app/sb-drive-client/id1444980912", "category": "Social"},
    # Intercity / CarPool
    {"key": "INTERCITY_MINIMUM_HOURS_LATER_BOOKING", "value": "2", "category": "Intercity"},
    {"key": "INTERCITY_RADIUS", "value": "100", "category": "Intercity"},
    {"key": "MAX_INTERCITY_DAYS", "value": "5", "category": "Intercity"},
    {"key": "RIDE_SHARE_BOOKING_FEE", "value": "5", "category": "CarPool"},
    {"key": "RIDE_SHARE_RECOMNENDED_PRICE", "value": "2", "category": "CarPool"},
    {"key": "MAX_ALLOWED_DAYS_FOR_CARPOOL", "value": "60", "category": "CarPool"},
    # Scheduled rides
    {"key": "MINIMUM_HOURS_LATER_BOOKING", "value": "60", "category": "Scheduled"},
    {"key": "MAXIMUM_HOURS_LATER_BOOKING", "value": "20160", "category": "Scheduled"},
    {"key": "BOOKING_LATER_ACCEPT_BEFORE_INTERVAL", "value": "30", "category": "Scheduled"},
    {"key": "BOOKING_LATER_ACCEPT_AFTER_INTERVAL", "value": "30", "category": "Scheduled"},
    {"key": "BOOKING_LATER_EXPIRE_AFTER_TIME", "value": "30", "category": "Scheduled"},
    # Extra
    {"key": "ENABLE_EXTRA_CHARGES_FOR_LATER_BOOKINGS", "value": "Yes", "category": "Extra"},
    {"key": "EXTRA_CHARGES_AMOUNT_TYPE", "value": "Percentage", "category": "Extra"},
    {"key": "EXTRA_CHARGES_AMOUNT", "value": "10", "category": "Extra"},
    {"key": "OUTSTANDING_ALLOW_TRIP_COUNT", "value": "1", "category": "Extra"},
    {"key": "ENABLE_24_HOUR_FORMAT", "value": "Yes", "category": "Extra"},
]

# ============================
# WALLET TRANSACTION TYPES
# From MySQL user_wallet table eFor enum
# ============================
WALLET_TRANSACTION_TYPES = [
    "Deposit", "Booking", "Refund", "Withdrawal",
    "Charges", "Referrer", "Transfer", "Subscription",
    "Outstanding", "Donation", "GiftCard"
]

# ============================
# TRIP PAYMENT MODES
# From MySQL trips table vTripPaymentMode enum
# ============================
PAYMENT_MODES = ["Cash", "Card", "Wallet", "Organization"]

# ============================
# TRIP STATUS FLOW
# From MySQL trips table iActive enum
# ============================
TRIP_STATUSES = ["Active", "Arrived", "On Going Trip", "Finished", "Canceled", "Inactive"]

# Mapped to our cleaner statuses
RIDE_STATUS_MAP = {
    "Active": "pending",
    "Arrived": "arriving",
    "On Going Trip": "in_progress",
    "Finished": "completed",
    "Canceled": "cancelled",
    "Inactive": "inactive",
}

# ============================
# FARE TYPES
# From MySQL vehicle_type eFareType enum
# ============================
FARE_TYPES = ["Regular", "Fixed", "Hourly"]
